"""Optimizer UI checks. Set TESTFLOW_REAL_STORAGE=1 for routed real localStorage.
Default offline mode explicitly uses an in-memory fixture. No production data.
"""
import json, os
from pathlib import Path
from playwright.sync_api import sync_playwright, expect
ROOT=Path(__file__).resolve().parents[1]
HTML=(ROOT/'index.html').read_text(encoding='utf-8')
OUTPUT=Path(os.environ.get('TESTFLOW_SCREENSHOTS','test-results/optimizer'))
OUTPUT.mkdir(parents=True,exist_ok=True)
REAL=os.environ.get('TESTFLOW_REAL_STORAGE')=='1'
checks=[]; errors=[]
def check(name): checks.append(name)
def attach(browser,width=1440,disable_worker=False):
    context=browser.new_context(viewport={'width':width,'height':1000},reduced_motion='reduce')
    context.route('**/*',lambda r:r.fulfill(status=200,content_type='text/html; charset=utf-8',body=HTML))
    if disable_worker: context.add_init_script('window.Worker=undefined')
    page=context.new_page();page.on('pageerror',lambda e:errors.append(str(e)))
    if REAL: page.goto('http://testflow.test/')
    else:
        page.evaluate("""() => { const data=new Map();Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,String(v)),removeItem:k=>data.delete(k)}}); }""")
        if disable_worker: page.evaluate('window.Worker=undefined')
        page.set_content(HTML)
    return page

def saved(page): return page.evaluate("JSON.parse(localStorage.getItem('testflow-plan-v2'))")
def import_plan(page,plan):
    page.locator('#import-file').set_input_files({'name':'fixture.json','mimeType':'application/json','buffer':json.dumps(plan,ensure_ascii=False).encode()})
    expect(page.locator('#toast')).to_contain_text('方案已载入')
def generate(page):
    page.locator('#optimizer-run').click()
    expect(page.locator('#optimizer-result-title')).to_be_visible(timeout=20000)
def number(page,key,value): page.locator('[data-opt-number="'+key+'"]').fill(str(value))
with sync_playwright() as p:
    executable=os.environ.get('TESTFLOW_CHROMIUM') or ('/usr/bin/chromium' if Path('/usr/bin/chromium').exists() else None)
    browser=p.chromium.launch(executable_path=executable,headless=True,args=['--no-sandbox'])
    page=attach(browser);original=saved(page);workers=[];page.on('worker',lambda w:workers.append(w))
    expect(page.locator('.operations-table th')).to_have_count(9)
    expect(page.locator('.operations-table .diagnostic-badge')).to_have_count(0)
    check('Operations table retains nine factual columns without duplicated labels')
    page.locator('[data-go-view="optimizer"]').first.click()
    expect(page.locator('#tab-optimizer')).to_have_attribute('aria-selected','true')
    generate(page)
    expect(page.locator('#optimizer-results')).to_contain_text('2 / 2')
    expect(page.locator('#optimizer-result-title')).to_contain_text('当前方案已达到')
    expect(page.locator('#optimizer-results')).to_contain_text('未设置可接受上限')
    assert saved(page)==original and len(workers)>0
    check('Explicit bounded search runs in a worker without changing the plan')
    page.locator('[data-opt-option="allowRotation"]').check()
    page.locator('[data-opt-option="allowArrival"]').check()
    expect(page.locator('#optimizer-result-title')).to_have_count(0)
    generate(page)
    expect(page.locator('#optimizer-results')).to_contain_text('14 / 14')
    expect(page.locator('#optimizer-results')).to_contain_text('需要权衡')
    check('Expanded scope and adverse metric tradeoffs are disclosed')
    page.locator('[data-opt-apply]').first.click()
    expect(page.locator('#optimizer-confirm')).to_be_visible()
    assert saved(page)==original
    page.get_by_role('button',name='保留当前方案',exact=True).click()
    assert saved(page)==original
    page.locator('[data-opt-apply]').first.click()
    page.locator('#optimizer-confirm-apply').click()
    after=saved(page)
    assert after['mode']=='分组轮转' and int(after['groups'])==5
    assert after['stations']==original['stations'] and after['breaks']==original['breaks']
    expect(page.locator('#optimizer-undo')).to_be_visible()
    page.locator('#optimizer-undo').click()
    assert saved(page)==original
    check('Confirmation, protocol preservation, and complete undo')
    page.locator('#optimizer-goal').select_option('wait');generate(page)
    expect(page.locator('#optimizer-results')).to_contain_text('优先减少人均累计等待')
    assert saved(page)==original
    check('Alternative objective is compared without automatic application')
    for key,val in [('meanLimit',10),('maxLimit',15),('peakLimit',18),('totalLimit',40)]:number(page,key,val)
    page.locator('#tab-stations').click()
    expect(page.locator('#capacity-diagnostics')).to_be_hidden()
    expect(page.locator('.optimizer-health')).to_contain_text('满足全部已设上限')
    expect(page.locator('#capacity-card')).to_be_visible()
    page.locator('#capacity-hint [data-diagnostic-action="details"]').click()
    expect(page.locator('#info-dialog')).to_be_visible()
    expect(page.locator('#info-content')).to_contain_text('当前未触发预警')
    page.locator('[data-close="info-dialog"]').click()
    expect(page.locator('#capacity-diagnostics')).to_be_hidden()
    check('Accepted limits suppress warning while optional details remain available')
    page.locator('#tab-optimizer').click();number(page,'meanLimit',0);generate(page)
    expect(page.locator('#optimizer-result-title')).to_contain_text('没有方案满足')
    expect(page.locator('[data-opt-apply]')).to_have_count(0)
    page.locator('#tab-stations').click()
    expect(page.locator('#capacity-diagnostics')).to_be_visible()
    expect(page.locator('#capacity-diagnostics')).to_contain_text('超出你设置的上限')
    check('Unreachable thresholds are not labeled acceptable or optimized')
    page.locator('#dismiss-diagnostics').click()
    page.locator('#tab-optimizer').click();number(page,'meanLimit',1);generate(page)
    page.locator('#tab-stations').click();expect(page.locator('#capacity-diagnostics')).to_be_hidden()
    check('Optimization preferences do not override plan-specific dismissal')
    page.locator('#tab-optimizer').click()
    page.locator('#optimizer-rules summary').click();number(page,'minSeconds',-1)
    expect(page.locator('#optimizer-run')).to_be_disabled();expect(page.locator('#optimizer-error')).not_to_be_empty()
    page.locator('#tab-people').click();page.locator('#tab-optimizer').click()
    expect(page.locator('#optimizer-run')).to_be_disabled()
    page.locator('#optimizer-rules summary').click();number(page,'minSeconds',60)
    expect(page.locator('#optimizer-run')).to_be_enabled()
    check('Invalid preference drafts remain invalid across view changes')
    for key in ['meanLimit','maxLimit','peakLimit','totalLimit']:number(page,key,'')
    generate(page);page.locator('#n').fill('25')
    expect(page.locator('#optimizer-result-title')).to_have_count(0)
    expect(page.locator('[data-opt-apply]')).to_have_count(0)
    check('Plan changes invalidate stale results and application controls')
    page.locator('#n').fill('24');generate(page)
    rest=dict(original,breaks=[{'name':'休息','enabled':True,'afterStage':2,'duration':300}])
    import_plan(page,rest);generate(page)
    expect(page.locator('#optimizer-results')).to_contain_text('保留休息位置')
    expect(page.locator('#optimizer-results')).to_contain_text('4 / 4')
    check('Rest semantics prevent unsafe scheduling-mode transitions')
    big=dict(original,n=500,stations=[dict(original['stations'][0],name='站点'+str(i),duration=30+i,cap=5) for i in range(20)])
    import_plan(page,big);page.locator('#optimizer-run').click();page.locator('#optimizer-cancel').click()
    expect(page.locator('#optimizer-progress')).to_contain_text('已停止比较')
    page.wait_for_timeout(100);expect(page.locator('#optimizer-result-title')).to_have_count(0)
    assert saved(page)==big
    check('Large worker comparison can be cancelled without plan mutation')
    small=dict(original,n=1,prep=0,close=0,breaks=[],stations=[dict(original['stations'][0],cap=1)])
    import_plan(page,small);page.locator('#tab-stations').click()
    expect(page.locator('#capacity-diagnostics')).to_be_hidden()
    expect(page.locator('.optimizer-health')).not_to_contain_text('满足全部已设上限')
    check('Balanced small plan is quiet without claiming undefined acceptability')
    import_plan(page,original);page.locator('#tab-optimizer').click()
    page.locator('#optimizer-goal').select_option('time');generate(page)
    page.wait_for_timeout(3600);page.evaluate('scrollTo(0,0)');page.screenshot(path=str(OUTPUT/'optimizer-desktop.png'),full_page=True)
    page.locator('#tab-stations').click();page.evaluate('scrollTo(0,0)');page.screenshot(path=str(OUTPUT/'stations-desktop.png'),full_page=True)
    for width in [320,390,768]:
        mobile=attach(browser,width);mobile.locator('#tab-optimizer').click();generate(mobile)
        assert mobile.evaluate('document.documentElement.scrollWidth <= innerWidth')
        mobile.evaluate('scrollTo(0,0)');mobile.screenshot(path=str(OUTPUT/f'optimizer-{width}.png'),full_page=True)
        mobile.close();check(f'No page overflow at {width}px')
    fallback=attach(browser,disable_worker=True);fallback.locator('#tab-optimizer').click();generate(fallback)
    expect(fallback.locator('#optimizer-results')).to_contain_text('2 / 2')
    check('Non-worker fallback retains bounded comparison behavior')
    page.locator('#tab-optimizer').click();number(page,'meanLimit',10)
    if REAL:page.reload()
    else:page.set_content(HTML)
    page.locator('#tab-optimizer').click()
    expect(page.locator('[data-opt-number="meanLimit"]')).to_have_value('10')
    assert saved(page)==original
    check('Preferences restore independently from the saved plan')
    browser.close()
assert not errors,errors
print(json.dumps({'optimizerBrowserChecks':len(checks),'storageMode':'real' if REAL else 'in-memory fixture','checks':checks,'pageErrors':errors},ensure_ascii=False))
